### ISSUE TITLE
use tcp router with http port forwarding

### ISSUE THREAD

**Issue by geohuz** [xmonader/nimdays#11]
I tried the code with forwarding to a http server, and I got the following error:

```
/nim-1.0.0/lib/pure/asyncfutures.nim(383)   read
  ]#
Exception message: index out of bounds, the container is empty
Exception type: [IndexError]
```

**Comment by xmonader** [comment]
I just tried and I can reproduce. definitely a bug.

**Comment by geohuz** [comment]
@xmonader do you have any idea on how to fix the issue, I just tried with newest 1.0.2 nim, still failed

**Comment by xmonader** [comment]
@geohuz I fixed it https://github.com/xmonader/nim-tcprouter/commit/6e6ab3bb7915c9a14b7fc68bec759b98b45636a0 not sure if it's a clean fix or not to be honest I sent it to the gitter chat for more help

**Comment by geohuz** [comment]
@xmonader sorry for the late reply, I just tested the lasted patch and it still failed with error output forever.
